### ISSUE TITLE
account details dropdown on right top corner does not have username

### ISSUE THREAD

**Issue by camaras** [camaras/linkspace#4]
After logging in, the account details dropdown on the top right hand corner should have the username on it.

**Comment by priyankush-siloria** [comment]
Will work on this next if not completed by you.

**Comment by camaras** [comment]
Yes, you can work on it.Thanks

    On Thursday, 26 March 2020, 7:10:30 am AEDT, priyankush-siloria <notifications@github.com> wrote:  
 
 


Will work on this next if not completed by you.

**Comment by camaras** [comment]
fixed by using {{ request.user.username}}
